// Generates the widget's strings from docs/copy.md so the copy has one source.
import { writeFileSync } from "node:fs";
import { ROOT, widgetStrings } from "./copy-lib.mjs";

const s = widgetStrings();
const out = `// GENERATED by scripts/gen-strings.mjs from docs/copy.md ("Widget strings"). Do not edit.\nexport const S = ${JSON.stringify(s, null, 2)} as const;\n`;
writeFileSync(ROOT + "packages/widget/src/strings.gen.ts", out);
console.log("strings: wrote packages/widget/src/strings.gen.ts", Object.keys(s).join(", "));
