// Demo strings. Everything in COPY must appear verbatim in docs/copy.md (tests/copy.test.ts checks).
// EXTRA lists text the demo needs that docs/copy.md does not have yet; most of it comes from the
// designer's prototypes (design/proto/*.html). It is flagged for the PM to add to docs/copy.md.

export const COPY = {
  brand: "Toll demo",
  navForms: "Forms",
  navHammer: "Bot hammer",
  navAgent: "Agent hammer",
  modeWorkOnly: "work-only",
  introTitle: "Every form on this page is protected",
  noPassTitle: "Try it without a pass",
  noPassButton: "Send without a pass",
  rejected403: "✕ Rejected · 403",
  runWithout: "50 writes without the check",
  runWith: "50 writes with the check",
  run50: "Run 50",
  statAccepted: "Accepted",
  statRejected: "Rejected",
  statMeanSolve: "Mean solve time",
  noJs: "This form needs JavaScript.",
} as const;

export const EXTRA = {
  introLede: "Use them like a normal visitor. Each one runs an invisible check in the background, and the counts on the right update as you go. Then try the same endpoint without a pass.",
  liveStats: "Live stats",
  contact: "Contact",
  contactSub: "A write. Gated as",
  comments: "Comments",
  commentsSub: "In-memory thread. Gated as write; your pass covers about 20 comments for 15 minutes.",
  addComment: "Add a comment",
  postComment: "Post comment",
  search: "Search",
  searchSub: "A search that POSTs. Gated as search (cheaper than a write).",
  noPassSub: "The same contact endpoint, called the way a script would.",
  name: "Name",
  email: "Email",
  message: "Message",
  send: "Send",
  sentPill: "✓ Accepted · 200",
  resultsFor: (n: number, q: string) => `${n} result${n === 1 ? "" : "s"} for "${q}"`,
  hammerTitle: "Bot hammer",
  hammerLede: "Fire 50 writes at the contact endpoint, first as a script that skips the check, then through the widget's background worker. Each square is one request.",
  runWithoutSub: "Plain POSTs, no worker, no pass.",
  runWithSub: "Each request solves in the worker first, like a visitor's browser.",
  accepted: "accepted",
  rejected: "rejected",
  meanSolve: "mean solve",
  legendAccepted: "✓ accepted",
  legendRejected: "✕ rejected",
  legendPending: "not sent yet",
  agentSub: "An automated client sends 20 writes with no widget. It pays each request instead of doing the work, using the test payment backend.",
  phase2: "phase 2",
} as const;
